name: Builds

on:
  push: { branches: [main] }
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  buildForAllPlatformsUbuntu:
    name: ${{ matrix.targetPlatform }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        projectName:
          - D3D_2020
        #cloudRunnerCluster:
        #  - local-docker
        #  - local
        #projectPath:
        #  - test-project
        # unityVersion:
          # - 2021.3.16f1
          # - 2021.3.15f1
          # - 2021.3.14f1
          # - 2021.3.13f1
          # - 2021.3.12f1
          # - 2021.3.11f1
          # - 2021.3.10f1
          # - 2021.3.9f1
          # - 2021.3.8f1
          # - 2021.3.7f1
          # - 2021.3.6f1
          # - 2021.3.5f1
          # - 2021.3.4f1
          # - 2021.3.3f1
          # - 2021.3.2f1
          # - 2021.3.1f1
          # - 2021.3.0f1
          # - 2021.2.19f1
          # - 2021.2.0f1
          # - 2021.1.28f1 - не работает
          # - 2021.0.0f1 - так же
          # - 2022.1.24f1
          # - 2022.1.23f1
          # - 2022.1.22f1
          # - 2022.1.21f1
          # - 2022.1.20f1
          # - 2022.1.19f1
          # - 2022.1.18f1
          # - 2022.1.17f1
          # - 2022.1.16f1
          # - 2022.1.15f1
          # - 2022.1.14f1
          # - 2022.1.13f1
          # - 2022.1.12f1
          # - 2022.1.11f1
          # - 2022.1.10f1
          # - 2022.1.9f1
          # - 2022.1.8f1
          # - 2022.1.7f1
          # - 2022.1.6f1
          # - 2022.1.5f1
          # - 2022.1.4f1
          # - 2022.1.3f1
          # - 2022.1.2f1
          # - 2022.1.1f1
          # # - 2022.1.0f1
          # - 2021.3.16f1
          # # - 2020.3.44f1
          # # - 2019.4.40f1
          # # - 2018.4.36f1
          # # - 2017.4.40f1
          # - 5.6.7f1
          # - 5.6.7
          # # - 2021.3.16f1
          # - 2021.3.15f1
          # - 2021.3.14f1
          # - 2021.3.13f1
          # - 2021.3.12f1
          # - 2021.3.11f1
          # - 2021.3.10f1
          # - 2021.3.9f1
          # - 2021.3.8f1
          # - 2021.3.7f1
          # - 2021.3.6f1
          # - 2021.3.5f1
          # - 2021.3.4f1
          # - 2021.3.3f1
          # - 2021.3.2f1
          # - 2021.3.1f1
          # # - 2021.3.0f1
          # # - 2021.2.19f1
          # # - 2021.2.0f1
          # # - 2021.1.28f1
          # # - 2021.1.0f1
          # # - 2023.1.0a26
          # # - 2023.1.0a25
          # # - 2023.1.0a12
        targetPlatform:
        #  - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
        #  - StandaloneLinux64 # Build a Linux 64-bit standalone.
        #  - iOS # Build an iOS player.
          # - Android # Build an Android .apk.
          # - WebGL # WebGL.
          #          - StandaloneWindows # Build a Windows standalone.
          #          - WSAPlayer # Build an Windows Store Apps player.
          #          - PS4 # Build a PS4 Standalone.
          #          - XboxOne # Build a Xbox One Standalone.
          #          - tvOS # Build to Apple's tvOS platform.
          #          - Switch # Build a Nintendo Switch player
    steps:
      ###########################
      #         Checkout        #
      ###########################
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      ###########################
      #          Cache          #
      ###########################
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.projectName }}-${{ matrix.targetPlatform }} #-${{ matrix.unityVersion }}
          restore-keys: |
            Library-${{ matrix.projectName }}-
            Library-

      ###########################
      #          Build          #
      ###########################
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          #projectPath: ${{ matrix.projectPath }}
          # unityVersion: ${{ matrix.unityVersion }}
          # buildName: ${{ matrix.projectName }}
          targetPlatform: ${{ matrix.targetPlatform }}
          # buildMethod: UnityBuilderAction.BuildScript.Build
          #customParameters: -profile SomeProfile -someBoolean -someValue exampleValue
          #cloudRunnerCluster: ${{ matrix.cloudRunnerCluster }}
          # allowDirtyBuild: true

      ###########################
      #          Upload         #
      ###########################
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
          retention-days: 14
          
      # - uses: Difegue/action-megacmd@master
        # with:
          # args: put -c build/${{ matrix.targetPlatform }} /Unity_projects/${{ matrix.projectName }}/${{ matrix.unityVersion }}/
        # env:
          # USERNAME: ${{ secrets.MEGA_USERNAME }}
          # PASSWORD: ${{ secrets.MEGA_PASSWORD }}